var annotated_dup =
[
    [ "_reent", "struct__reent.html", "struct__reent" ],
    [ "AppMetadata", "structAppMetadata.html", "structAppMetadata" ],
    [ "BigInt", "classBigInt.html", "classBigInt" ],
    [ "Button", "classButton.html", "classButton" ],
    [ "CheckBox", "classCheckBox.html", "classCheckBox" ],
    [ "Color", "classColor.html", "classColor" ],
    [ "ColorValueException", "classColorValueException.html", "classColorValueException" ],
    [ "Display", "classDisplay.html", "classDisplay" ],
    [ "FILE", "structFILE.html", "structFILE" ],
    [ "Hscroll", "classHscroll.html", "classHscroll" ],
    [ "Image", "classImage.html", "classImage" ],
    [ "ListView", "classListView.html", "classListView" ],
    [ "Point", "classPoint.html", "classPoint" ],
    [ "ProgressBar", "classProgressBar.html", "classProgressBar" ],
    [ "RadioButton", "classRadioButton.html", "classRadioButton" ],
    [ "Rect", "classRect.html", "classRect" ],
    [ "RoundButton", "classRoundButton.html", "classRoundButton" ],
    [ "s_buf", "structs__buf.html", "structs__buf" ],
    [ "s_font", "structs__font.html", "structs__font" ],
    [ "s_font_context", "structs__font__context.html", "structs__font__context" ],
    [ "s_format", "structs__format.html", "structs__format" ],
    [ "s_HTMLColor", "structs__HTMLColor.html", "structs__HTMLColor" ],
    [ "s_list", "structs__list.html", "structs__list" ],
    [ "s_point", "structs__point.html", "structs__point" ],
    [ "Size", "classSize.html", "classSize" ],
    [ "string", "classstring.html", "classstring" ],
    [ "Switch", "classSwitch.html", "classSwitch" ],
    [ "sxml_args_t", "structsxml__args__t.html", "structsxml__args__t" ],
    [ "sxml_t", "structsxml__t.html", "structsxml__t" ],
    [ "sxmltok_t", "structsxmltok__t.html", "structsxmltok__t" ],
    [ "Text", "classText.html", "classText" ],
    [ "TextBox", "classTextBox.html", "classTextBox" ],
    [ "Vscroll", "classVscroll.html", "classVscroll" ],
    [ "WebView", "classWebView.html", "classWebView" ]
];