#!/bin/bash

display() {
	clear
	title=$1
	text=$2
	percentage=£3

	# colors
	OUTLINE_COLOR="\e[93m"
	BACKGROUND_COLOR="\e[93m"
	WINDOW_BACKGROUND_COLOR="\e[93m"
	TEXT_COLOR="\e[93m"
	


	TERMINAL_W=$(tput cols)
	TERMINAL_H=$(tput lines)

	LINES=5
	WINDOW_H=$LINES+2
	WINDOW_W=10

	TITLE_LEN=${#title}
	TOP_HOR_OUTLINE_W=($TERMINAL_W-2-4-$TITLE_LEN)/2
	BOTTOM_HOR_OUTLINE_W=($TERMINAL_W-2)


	# creates text content
	for (( i = 0; i < $TERMINAL_W-${#TEXT}; i++ )); do
		TEXT_CONTENT=$TEXT_CONTENT+" "
	done
	

	# first line

	echo -n "┌"
	for (( i = 0; i < $TOP_HOR_OUTLINE_W; i++ )); do
		echo -n "─"
	done
	echo -n "┤ ${title} ├"
	for (( i = 0; i < $TOP_HOR_OUTLINE_W; i++ )); do
		echo -n "─"
	done
	echo "┐"


	# text lines
	for (( i = 0; i < $TERMINAL_H-2; i++ )); do
		echo -n "│"
		for (( j = 0; j < $TERMINAL_W-2; j++ )); do
			echo -n " "
		done
		echo -n "│"
	done


	# last line
	echo -n "└"
	for (( i = 0; i < $BOTTOM_HOR_OUTLINE_W; i++ )); do
		echo -n "─"
	done
	echo "┘"
}


while true; do
	clear
	display "my title" "test"
	read -r -s input
done









 # ┌──────────────────────────────────────────────┤ Installing packages ├──────────────────────────────────────────────┐
 # │ Retrieving file 21 of 260 (7min 53s remaining)                                                                    │
 # │                                                                                                                   │
 # │                                                                                                                   │
 # │                                                                                                                   │
 # │                                                         0%                                                        │
 # │                                                                                                                   │
 # └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘










