[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "d3m0n OS"
authors = [{name = "4re5 group", email = "4re5@gmail.com"}]
dynamic = ["version", "description"]
