#ifndef SETTINGS_H
#define SETTINGS_H

#define STRING_SIZE	128

typedef struct s_conf
{
	// style
	char	wallpaper[STRING_SIZE];
	int		theme;
	int		splash_time;

	// clock
	int		time_mode;

	// launcher
	char	launcher[STRING_SIZE];


	// icons
	char	icon_pack[STRING_SIZE];
	// wifi
	char	icon_airplane_mode[STRING_SIZE];
	char	icon_wifi_lock[STRING_SIZE];
	char	icon_wifi_off[STRING_SIZE];
	char	icon_wifi_level0[STRING_SIZE];
	char	icon_wifi_level1[STRING_SIZE];
	char	icon_wifi_level2[STRING_SIZE];
	char	icon_wifi_level3[STRING_SIZE];
	char	icon_wifi_level4[STRING_SIZE];
	char	icon_wifi_lock_level1[STRING_SIZE];
	char	icon_wifi_lock_level2[STRING_SIZE];
	char	icon_wifi_lock_level3[STRING_SIZE];
	char	icon_wifi_lock_level4[STRING_SIZE];
	// battery
	char	icon_battery_20[STRING_SIZE];
	char	icon_battery_30[STRING_SIZE];
	char	icon_battery_50[STRING_SIZE];
	char	icon_battery_60[STRING_SIZE];
	char	icon_battery_80[STRING_SIZE];
	char	icon_battery_90[STRING_SIZE];
	char	icon_battery_100[STRING_SIZE];
	char	icon_battery_alert[STRING_SIZE];
	char	icon_battery_charging_20[STRING_SIZE];
	char	icon_battery_charging_30[STRING_SIZE];
	char	icon_battery_charging_50[STRING_SIZE];
	char	icon_battery_charging_60[STRING_SIZE];
	char	icon_battery_charging_80[STRING_SIZE];
	char	icon_battery_charging_90[STRING_SIZE];
	char	icon_battery_charging_100[STRING_SIZE];
	char	icon_battery_standard[STRING_SIZE];
	char	icon_battery_unknown[STRING_SIZE];
	// bluetooth
	char	icon_bluetooth[STRING_SIZE];
	char	icon_bluetooth_connected[STRING_SIZE];
	char	icon_bluetooth_disabled[STRING_SIZE];
	char	icon_bluetooth_searching[STRING_SIZE];
	// cellular signal
	char	icon_cellular_level0[STRING_SIZE];
	char	icon_cellular_level1[STRING_SIZE];
	char	icon_cellular_level2[STRING_SIZE];
	char	icon_cellular_level3[STRING_SIZE];
	char	icon_cellular_level4[STRING_SIZE];
	char	icon_cellular_no_internet0[STRING_SIZE];
	char	icon_cellular_no_internet1[STRING_SIZE];
	char	icon_cellular_no_internet2[STRING_SIZE];
	char	icon_cellular_no_internet3[STRING_SIZE];
	char	icon_cellular_no_internet4[STRING_SIZE];
	char	icon_cellular_off[STRING_SIZE];
	char	icon_cellular_no_sim[STRING_SIZE];
	char	icon_cellular_null[STRING_SIZE];
	char	icon_cellular_alt[STRING_SIZE];
	// storage
	char	icon_sd_storage[STRING_SIZE];
	// system
	char	icon_settings[STRING_SIZE];
	char	icon_search[STRING_SIZE];
	char	icon_home[STRING_SIZE];
	char	icon_lock[STRING_SIZE];
	char	icon_lock_open[STRING_SIZE];
	char	icon_power[STRING_SIZE];
	char	icon_backup[STRING_SIZE];
	char	icon_restore[STRING_SIZE];
	char	icon_sync[STRING_SIZE];
	char	icon_sync_disabled[STRING_SIZE];
	char	icon_cached[STRING_SIZE];
	// user
	char	icon_account[STRING_SIZE];
	char	icon_visibility[STRING_SIZE];
	char	icon_visibility_off[STRING_SIZE];
	char	icon_favorite[STRING_SIZE];
	char	icon_favorite_border[STRING_SIZE];
	// status
	char	icon_error[STRING_SIZE];
	char	icon_warning[STRING_SIZE];
	char	icon_notification[STRING_SIZE];
	char	icon_info[STRING_SIZE];
	char	icon_help[STRING_SIZE];
	char	icon_bug_report[STRING_SIZE];
	// time
	char	icon_alarm[STRING_SIZE];
	char	icon_alarm_on[STRING_SIZE];
	char	icon_alarm_off[STRING_SIZE];
	char	icon_schedule[STRING_SIZE];
	char	icon_today[STRING_SIZE];
	char	icon_event[STRING_SIZE];
	char	icon_history[STRING_SIZE];
	// media
	char	icon_play[STRING_SIZE];
	char	icon_pause[STRING_SIZE];
	char	icon_stop[STRING_SIZE];
	char	icon_next[STRING_SIZE];
	char	icon_previous[STRING_SIZE];
	char	icon_fast_forward[STRING_SIZE];
	char	icon_fast_rewind[STRING_SIZE];
	// audio
	char	icon_volume_up[STRING_SIZE];
	char	icon_volume_down[STRING_SIZE];
	char	icon_volume_mute[STRING_SIZE];
	char	icon_volume_off[STRING_SIZE];
	char	icon_mic[STRING_SIZE];
	char	icon_mic_off[STRING_SIZE];
	char	icon_headset[STRING_SIZE];
	char	icon_speaker[STRING_SIZE];
	// camera
	char	icon_camera[STRING_SIZE];
	char	icon_camera_alt[STRING_SIZE];
	char	icon_photo[STRING_SIZE];
	char	icon_photo_camera[STRING_SIZE];
	char	icon_flash_on[STRING_SIZE];
	char	icon_flash_off[STRING_SIZE];
	char	icon_videocam[STRING_SIZE];
	char	icon_videocam_off[STRING_SIZE];
	// communication
	char	icon_phone[STRING_SIZE];
	char	icon_call[STRING_SIZE];
	char	icon_call_end[STRING_SIZE];
	char	icon_contacts[STRING_SIZE];
	char	icon_chat[STRING_SIZE];
	char	icon_message[STRING_SIZE];
	char	icon_email[STRING_SIZE];
	char	icon_phone_locked[STRING_SIZE];
	char	icon_phone_missed[STRING_SIZE];
	char	icon_phonelink_ring[STRING_SIZE];
	// editing
	char	icon_add[STRING_SIZE];
	char	icon_remove[STRING_SIZE];
	char	icon_clear[STRING_SIZE];
	char	icon_create[STRING_SIZE];
	char	icon_save[STRING_SIZE];
	char	icon_send[STRING_SIZE];
	char	icon_paste[STRING_SIZE];
	char	icon_sort[STRING_SIZE];
	char	icon_filter[STRING_SIZE];
	char	icon_delete[STRING_SIZE];
	// location
	char	icon_place[STRING_SIZE];
	char	icon_navigation[STRING_SIZE];
	char	icon_my_location[STRING_SIZE];
	char	icon_gps_fixed[STRING_SIZE];
	char	icon_gps_searching[STRING_SIZE];
	char	icon_gps_location_searching[STRING_SIZE];
	char	icon_gps_off[STRING_SIZE];
	char	icon_location_disabled[STRING_SIZE];
	char	icon_location_searching[STRING_SIZE];
	// display
	char	icon_brightness_low[STRING_SIZE];
	char	icon_brightness_medium[STRING_SIZE];
	char	icon_brightness_high[STRING_SIZE];
	char	icon_brightness_auto[STRING_SIZE];
	// connectivity
	char	icon_network_cell[STRING_SIZE];
	char	icon_network_wifi[STRING_SIZE];
	char	icon_data_usage[STRING_SIZE];
	char	icon_nfc[STRING_SIZE];
	// hardware
	char	icon_sim_card[STRING_SIZE];
	char	icon_memory[STRING_SIZE];
	char	icon_keyboard[STRING_SIZE];
	char	icon_keyboard_up[STRING_SIZE];
	char	icon_keyboard_down[STRING_SIZE];
	char	icon_keyboard_left[STRING_SIZE];
	char	icon_keyboard_right[STRING_SIZE];
	char	icon_smartphone[STRING_SIZE];
	// toggles
	char	icon_checkbox_checked[STRING_SIZE];
	char	icon_checkbox_unchecked[STRING_SIZE];
	char	icon_radio_checked[STRING_SIZE];
	char	icon_radio_unchecked[STRING_SIZE];
	char	icon_toggle_on[STRING_SIZE];
	char	icon_toggle_off[STRING_SIZE];
}	t_conf;

int		parse_config(t_conf *config);
t_conf	*get_config();
char	*get_setting(const char *path, const char *key, int	*not_found);
int		set_setting(const char *path, const char *key, const char *value);

#endif