name: compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies install
      run: sudo apt install gcc-arm-none-eabi -y
    - name: make
      run: make
